RUN wget https://s3-us-west-2.amazonaws.com/openai-sci-artifacts/manual-builds/patchelf_0.9_amd64.elf -O /usr/local/bin/patchelf
RUN chmod +x /usr/local/bin/patchelf

# Install mujoco
RUN mkdir -p /opt/mujoco
RUN wget https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz -O /opt/mujoco/mujoco210-linux-x86_64.tar.gz
RUN tar xf /opt/mujoco/mujoco210-linux-x86_64.tar.gz -C /opt/mujoco
RUN rm /opt/mujoco/mujoco210-linux-x86_64.tar.gz
ENV MUJOCO_PY_MUJOCO_PATH /opt/mujoco/mujoco210
ENV LD_LIBRARY_PATH /opt/mujoco/mujoco210/bin:${LD_LIBRARY_PATH}


# Install gym
RUN pip install gym mujoco imageio mujoco-py
RUN python -c "from gym.envs.mujoco.mujoco_env import MujocoEnv"

# Modify the env variable
ENV USER_REOWN_PATHS /usr/local/lib/python3.8/dist-packages/mujoco_py
